name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    types: ["closed"]
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ${{ github.repository }} .
      - name: Deploy image
        run: |
          docker stop ${{ github.event.repository.name }} || true
          docker rm ${{ github.event.repository.name }} || true
          docker run -d --restart always -e "TOKEN=${{ secrets.TOKEN }}" --name ${{ github.event.repository.name }} ${{ github.repository }}
